### ISSUE TITLE
Enable/Disable individual or all rules

### ISSUE THREAD

**Issue by cafestifflered** [cafestifflered/ChatRestrict#1]
When running '/chatrestrict toggle' or '/chatrestrict enable' commands, the plugin correctly says that the players are now unable to talk, but the players can actually still talk even without the bypass permission.

**Comment by cafestifflered** [comment]
Changing the scope of the fix for this.

We will add a new param to the rules/predicates: `enabled: true`

Example:
```
rules:
  chat-disabled-days:
    enabled: true
    type: "valid_weekdays"
    week_days: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]
    zone: "EST"
  chat-disabled-time:
    enabled: true
    type: "valid_timerange"
    time_min: "0:00 AM"
    time_max: "0:00 AM"
    zone: "EST"
```

Rules can be enabled or disabled individually either via the config file or a command. With commands, the format looks like:
`/chatrestrict <enable/disable> <rulename>`
`/chatrestrict <enable/disable>`

<rulename> should tab-autocomplete. The first command will only disable/enable a specific rule. The second command will enable/disable all rules.

Change these two lines in config.yml
```
      override-disabled: '<green>Players are now able to talk.'
      override-enabled: '<yellow>Players are now unable to talk.'
```
To be:
```      rule-disabled: '<green><rulename> is now disabled. <list rule description>'
      rule-enabled: '<yellow><rulename> is now enabled. <list rule description>'
      all-rules-disabled: '<green>All rules are disabled and players are able to talk.'
      all-rules-enabled: '<yellow>All rules are enabled and players may not be able to talk.'```
