### ISSUE TITLE
New rule type for chat filtering

### ISSUE THREAD

**Issue by cafestifflered** [cafestifflered/ChatRestrict#7]
Allow creating a rule that looks at the message for specific words. If the words match, block the message from being sent.

This will be used as a chat, advert, or spam filter.

Might be best to create a new wordfilter.yml file for these types of rules just to separate them out from the other rules for easier organization. Same rule format, though.

### Example:
```
blocked-words:
  type: "chat_filter"
  regex: true
  words: ["oof", "uwu"]
```
This would block a message sent by a player including "oof", as well as "o of", "o.o.f", etc...
